### ISSUE TITLE
get_token does not work now 

### ISSUE THREAD

**Issue by medhatzak86** [anadius/ea-get-token#1] opened 2024-03-15 13:09 UTC
get_token does not work now

**Comment by anadius** [comment] 2024-03-15 13:59
I have EA app version 13.152.0.5665 and use "get token" version 1.0.2 - works fine. Disable autostart in EA app settings, reboot, try again.

**Comment by medhatzak86** [comment] 2024-03-15 14:16
![123](https://github.com/anadius/ea-get-token/assets/145803386/7b847597-fa2a-41df-b586-df3c6f83b935)
i have also  EA app version 13.152.0.5665 and token is too long as pic attached

**Comment by anadius** [comment] 2024-03-15 14:20
It's not too long. That's the new format. I deleted your screenshot because with that stuff someone could get access to your account. I'm closing this issue since everything works as intended.

And if you get some error in Origin Helper - it's because you use an outdated version, I already updated it at the same time I updated this program.

**Closed by anadius** 2024-03-15 14:20 UTC
